from relative_traceback import use_relative_except


use_relative_except()
1 / 0
